security:

    # ── Hashage des mots de passe ─────────────────────────────────────
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    # ── Fournisseur d'utilisateurs ────────────────────────────────────
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                # Symfony cherchera l'utilisateur par son email
                property: email

    # ── Firewalls ─────────────────────────────────────────────────────
    firewalls:

        # Firewall pour les outils de développement (profiler, etc.)
        # security: false = pas d'auth requise pour ces routes
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal — s'applique à tout le site
        main:
            lazy: true
            provider: app_user_provider

         
            user_checker: App\Security\UserChecker

            # Formulaire de login standard Symfony
            form_login:
                # Route vers le formulaire de connexion
                login_path: app_login
                # Route qui traite le POST du formulaire
                check_path: app_login
                # Redirige vers /login après connexion
                # SecurityController prend ensuite le relais pour router selon le rôle
                default_target_path: app_login
                use_referer: false

            # Déconnexion
            logout:
                # Route de déconnexion
                path: app_logout
                # Redirection après déconnexion
                target: app_home

    # ── Contrôle d'accès ──────────────────────────────────────────────

    access_control:
        # /admin et toutes les sous-routes nécessitent ROLE_ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }
        # /login est accessible à tous (PUBLIC_ACCESS)
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/verify/email, roles: PUBLIC_ACCESS }
        # Tout le reste est accessible à tous
        - { path: ^/, roles: PUBLIC_ACCESS }